name: Build Wasm component from Rust and push to OCI registry

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup wash CLI
        uses: wasmcloud/setup-wash-action@v1.0.0-rc.3

      - name: Build Wasm component
        id: build
        uses: wasmCloud/actions/wash-build@v0.2.0
        with:
          working-directory: ./hello-world

      - name: Publish Wasm component
        uses: wasmcloud/actions/wash-oci-publish@v0.2.0
        with:
          component_path: ${{ steps.build.outputs.component_path }}
          image_tags: ${{ github.ref_name }}

      - name: Update image tag in Kubernetes manifest
        working-directory: ./hello-world
        run: |
          DEPLOYMENT_FILE="manifests/workloaddeployment.yaml"
          OLD_IMAGE=$(grep "image:" "$DEPLOYMENT_FILE" | awk '{print $2}')
          NEW_IMAGE="ghcr.io/${{ env.GHCR_REPO_NAMESPACE }}/components/hello-world:${{ github.ref_name }}"

          # Update the image tag
          sed -i "s|image:.*|image: $NEW_IMAGE|" "$DEPLOYMENT_FILE"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            Update image tag in manifest to ${{ github.ref_name }}
          title: Update image tag in manifest to ${{ github.ref_name }}
